"""estado inicial del esquema

Revision ID: a13be0302110
Revises: 
Create Date: 2026-09-20 15:38:37.403913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a13be0302110'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('industria', sa.String(length=100), nullable=True),
    sa.Column('sitio_web', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('salario_estimado', sa.Integer(), nullable=True),
    sa.Column('modalidad', sa.String(length=20), nullable=True),
    sa.Column('tecnologias', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('fecha_publicacion', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aplicaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacante_id', sa.Integer(), nullable=False),
    sa.Column('fecha_aplicacion', sa.Date(), nullable=False),
    sa.Column('estatus', sa.Enum('APLICADO', 'ENTREVISTA', 'OFERTA', 'RECHAZADO', name='estatus_aplicacion'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vacante_id'], ['vacantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aplicaciones')
    op.drop_table('vacantes')
    op.drop_table('empresas')
    # ### end Alembic commands ###
